spring:
  datasource:
    url: jdbc:mysql://rm-wz9e8j7rnq3wn2ak6no.mysql.rds.aliyuncs.com:3306/adplat?useAffectedRows=true&amp;allowMultiQueries=true&amp;useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: adplat
    password: Batiaohaohan@123
    driver-class-name: com.mysql.cj.jdbc.Driver